# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: firsttracks

# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fafauth-api

# "service" is the name of this project. This will also be added to your AWS resource names.
service: fafauth-ap-south-1

provider:
    name: aws
    runtime: python3.14

functions:
    apiCustomAuthorizer:
        handler: handler.custom_authorizer
